# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06e4d6f33e3dcd26894a0e5fd0951eef8087c7c2170c8daebcb7f9e764bfcd9621b705ae4fbeaf0e23a3154a646350a2a14784ebf2168bb1cd16281897786cdc

test:
  secret_key_base: 523e845ecdbd81a5f2892f0523c08ec01ce7dc72623b49f4f18208c543bac51c1a62eb4044b0638ae90f69b4cc99326cad4d7d695af8880bd0864486644b6902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
